### PR TITLE
Stabby proc and attr init

### PR DESCRIPTION
**Pull request by deanrad**
Yang, this branch contains a merged version of both previous pull requests. Specs should explain pretty well. In the future I'll probably open issues first to discuss, but if this code works for you, please feel free to take it.. If it needs more love - let me know ! 

PS - I've submitted a talk for RailsConf on reactive programming-  I'll know in a week if they accept-  yours is the library I intend to base the talk on - thus my increased interest of late for contributing :)

### CODE REVIEW

**Comment by yang** [comment]
Cool, thanks for the syntax extensions and cleanup! The only two issues I can see right now with attribute initialization are:
- ambiguity: `div '#foo'` is treated as content rather than ID (understandably)
- dynamism: `div '.bar', {class: bind -> 'modifier' if someCondition.get()}` (but we can just say this isn't supported)

I'm a bit more confused on the stabby procs though - looks like this is still early and doesn't support multiple children, right?  (Would need some global to track all the constructions inside a scope.)  I'm thinking it would be cleaner to start a separate DSL module (sibling to `rxt.tags`) to experiment with these - would be less complex both ways to not be tied to existing `mktag`.

Re: your talk - wow, that's huge! I hope it gets accepted. Let me know if I can help out in other ways.

**Comment by yang** [comment]
(I'm going to merge in #25 instead)

EDIT: Oops, never mind - I can't merge that in (closed)....

**Comment by deanrad** [comment]
Good suggestions on both - you're right, stabby procs is immature yet, and I think I could table it for a while and do it separately from mktag if at all. Meanwhile if you like where #25 was going I'll reopen it and add tests around the scenarios you described.

**Comment by yang** [comment]
I think both of these ideas are very worthy of exploration. Yeah sounds good, go ahead and re-open #25 - that one seems like a relative light change that provides some convenience/less typing for users of Jade etc.

**Pull request closed without merging**
